services:
  web:
    container_name: task_backend
    build: .
    command: sh -c "python manage.py migrate &&
                    uvicorn config.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
    expose:
      - "8000"
    ports:
      - "8001:8000"
    restart: on-failure
    depends_on:
      - db
      - redis
    networks:
      - task-network
      - project-network

  db:
    image: postgres:16
    container_name: task_db
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - pgdata:/var/lib/postgresql/data/
    networks:
      - task-network
  
  redis:
    container_name: task_redis
    image: redis:latest
    networks:
      - task-network
  
  rabbitmq:
    container_name: task_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - task-network
  
  celery:
    environment:
      - C_FORCE_ROOT="true"
    build: .
    container_name: task_celery
    command: "celery -A config worker -l info"
    depends_on:
      - web
    restart: on-failure
    networks:
      - task-network
  
  celery_beat_worker:
    build: .
    command: sh -c "celery -A config.celery beat -l INFO"
    depends_on:
      - celery
    restart: on-failure
    networks:
      - task-network
  
  subscriber:
    build: .
    command: python subscriber.py
    restart: always
    depends_on:
      - db
    networks:
      - task-network
      - project-network

volumes:
  pgdata:

networks:
  task-network:
  project-network:
    external: true